import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className="w-[100vw] h-[100vh] flex items-center justify-center">
      <Head>
        <title>Mini Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link
        href={{
          pathname: '/post',
        }}
        className="text-3xl text-bold"
      >
        블로그 보러가기
      </Link>
    </div>
  );
};

export default Home;
